### ISSUE TITLE
How can I re-use this code?

### ISSUE THREAD

**Issue by shahaamirbader** [liuzuxin/OSRL#12]
Although you mentioned that your code is inspired by CORL but I find differences as well other than CTG. Can you help me understand your code better by answering the following:

1. What are the major differences of your code from the CORL other than the CTG and why?
2. If I re-use this codebase for one of my projects do I cite you or the CORL?
3. What steps will I need to take to include another parameter similar to CTG on the existing architecure. Let's say in addition to RTG and CTG I would like to add another feature such as Distance-to-go, how can I include that?
4. What all files (model, training, evaluation, visualization, results etc) makeup just the CTD. I would like to isolate all the CTD code from this code-base to work on something like in point 3. 

Thanks

**Comment by liuzuxin** [comment]
1. There are many differences, and the major ones are mentioned in the paper: 1) a stochastic policy head instead of the deterministic one in CORL, and 2) the data augmentation phase. 
2. You should cite the [CDT](https://arxiv.org/abs/2302.07351) paper and this [benchmark](https://arxiv.org/abs/2306.09303) paper. I will update these bibtex in the repo readme file later. You are also welcome to discuss CORL if you think you will also use code from their repo.
3. It is not difficult to achieve that, just duplicate every part related to cost in the CDT mode implementation with your other metrics-to-go. I think it requires you to have a good understanding of the model architecture and the code, so please read carefully regarding the model implementation.
4. Since we use similar single-file implementation structure as CORL, the CDT implementation only depends on `osrl.common.net`, so it would be pretty convenient to isolate this algorithm.

**Comment by shahaamirbader** [comment]
Thanks that is a very convincing response. Closing this.
