### ISSUE TITLE
I want to write an environment for CDT to run, how do I do it？

### ISSUE THREAD

**Issue by 623637719** [liuzuxin/OSRL#17]
I successfully install your code and successfully run the code on train_cdt.py.
I want to write an environment for CDT to run, how do I do it？

Here are the details of my computer: 
![image](https://github.com/liuzuxin/OSRL/assets/111236370/3eeeb4e5-3cae-4dfe-b36e-ad9ed037b95c)

**Comment by liuzuxin** [comment]
Hi, would you mind providing more information about `I want to write an environment for CDT to run`? What environment do you want to write?

**Comment by 623637719** [comment]
> Hi, would you mind providing more information about `I want to write an environment for CDT to run`? What environment do you want to write?

I'm sorry that my expression is not very accurate. Such as in cdt_configs. py, I can choose a task called "OfflinePointCircle2Gymnasium - v0"
![image](https://github.com/liuzuxin/OSRL/assets/111236370/8a855018-ae8b-4eca-8252-cde1247d5989)

Then in train_cdt.py，I can make a environment through “gym.make(args.task)”
![image](https://github.com/liuzuxin/OSRL/assets/111236370/70b056da-820e-45cb-ab23-383a0f34dc2d)

My question is, I want to leave the tran_cdt.py unchanged and write an environment that can also be run by it. How do I do that? I know that such environments need function like step(), reset(), etc., but I don't know how I add the new environment.

**Comment by Ja4822** [comment]
Hi @623637719, as you mentioned, to craft you own custom environments, functions such as step(), reset(), etc must be defined. You may find this [Gym Documentation](https://www.gymlibrary.dev/content/environment_creation/#) helpful. 
You can refer to [DSRL](https://github.com/liuzuxin/DSRL) that maintains the offline environments used in OSRL for how to wrap and register your custon environemnts. [D4RL](https://github.com/Farama-Foundation/D4RL/tree/master/d4rl)  is also a great reference for this process.
Note that in OSRL and DSRL, we use [gymnasium](https://github.com/Farama-Foundation/Gymnasium) rather than gym so make sure that your environments are compatible with gymnasium. For compatibility issue please refer to [this](https://gymnasium.farama.org/content/gym_compatibility/) and [this](https://gymnasium.farama.org/content/migration-guide/).

**Comment by 623637719** [comment]
Thank you very much ！ Please close this.

> Hi @623637719, as you mentioned, to craft you own custom environments, functions such as step(), reset(), etc must be defined. You may find this [Gym Documentation](https://www.gymlibrary.dev/content/environment_creation/#) helpful. You can refer to [DSRL](https://github.com/liuzuxin/DSRL) that maintains the offline environments used in OSRL for how to wrap and register your custon environemnts. [D4RL](https://github.com/Farama-Foundation/D4RL/tree/master/d4rl) is also a great reference for this process. Note that in OSRL and DSRL, we use [gymnasium](https://github.com/Farama-Foundation/Gymnasium) rather than gym so make sure that your environments are compatible with gymnasium. For compatibility issue please refer to [this](https://gymnasium.farama.org/content/gym_compatibility/) and [this](https://gymnasium.farama.org/content/migration-guide/).
